version: '3.9'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=bobo
      - POSTGRES_PASSWORD=bobo
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/resto
      - SPRING_DATASOURCE_USERNAME=bobo
      - SPRING_DATASOURCE_PASSWORD=bobo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=bobo
      - POSTGRES_PASSWORD=bobo
      - POSTGRES_DB=resto